# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85d1e1a7e37366c6a46ac96969608daa0837fafa8df61e8b18e805eea5e6c4a41f09d2447b841e25f3d7ec65efcbb34492dc85dd9db7ed0f30acf9374e893f0b

test:
  secret_key_base: b6581c1fb6b0e63ee1c889aac049db85e8c6311f3e2b83af36531396bfe6ba278c331b24ba82b9e6f810335d67424de57266275d5be3ca5208370ca23f4c0808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
