source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in ft_wikipedia.gemspec
gemspec
gem ft_wikipedia
gem 'nokogiri', '1.8.2', :require => "nokogiri"
