# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1bfec1253674e3b84f56a69e2c946cd194b09edf1bdd8f843783ebea2502f942103c378afb45b1928b960bad709c9781982d78b3837bea825f226b97bef24fd

test:
  secret_key_base: dfca69e01536c9c0bf3b1eb60459dc9e747a2287d17898b56c9d55a1eab4acaab9ee9132eaf737ec399adc293ce863409cdf395c994d64b433eca60e88bcc5fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
